format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$docker_context\
"""

add_newline = false

[directory]
format = "$path  "
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"~/Documents/" = " "
"~/Documents" = ""
"~/Downloads/" = " "
"~/Downloads" = ""
"~/Music/" = " "
"~/Music" = ""
"~/Pictures/" = " "
"~/Pictures" = ""
"~/saffron/" = " "
"~/saffron" = ""
"~/code/" = " "
"~/code" = ""
"~/.config/" = " "
"~/.config" = ""

[docker_context]
symbol = " "
format = '$symbol $context $path'

[git_branch]
symbol = ""
format = '$symbol $branch'

[git_status]
format = '$all_status$ahead_behind  '

[nodejs]
symbol = ""
format = '$symbol ($version)  '

[rust]
symbol = ""
format = '$symbol ($version)  '
